services:
  - type: web
    name: careflow-backend
    runtime: java
    rootDir: careflow-backend
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    plan: free